import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import 'react-loading-skeleton/dist/skeleton.css'
import AuthProvider from '@/components/providers/AuthProvider';

const lato = Lato({ subsets: ['latin'],weight: ["300","400","700"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
